# Creates the mysql and apache2 servers needed for Foodiegram to work.
# To start them, having docker installed, open a terminal inside the compose
# and type "docker-compose up"-

version: "3.3"

services:

  foodiegramDB:
    image: mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=cr7
      - MYSQL_DATABASE=foodiegram

    volumes:
      - foodiegramDB:/var/lib/mysql
      - type: bind
        source: ./BD
        target: /docker-entrypoint-initdb.d
      
    ports:
      - 3306:3306

  apache:
    
    build: .
    
    volumes: 
      - type: bind
        source: ./images
        target: /usr/local/apache2/htdocs

    ports:
      - 4555:4555

 

volumes:
  foodiegramDB: